version: "3.9"

networks:
  netology:

services:

  postgres_db:
    image: postgres:14.6-alpine3.16
    ports:
      - "5500:5432"
    environment:
      POSTGRES_DB: adverts_api_db_1
      POSTGRES_USER: adv_admin
      POSTGRES_PASSWORD: qwerty123
    networks:
      netology:
        aliases:
          - postgre_db

  app:
    build:
      context: ./app
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    volumes:
      - ./app:/app
    networks:
      netology:
        aliases:
          - api